# Generated by Django 4.0.2 on 2022-06-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydroshine',
            options={'verbose_name': 'Hydro Shine', 'verbose_name_plural': 'Hydro Shine'},
        ),
    ]
