# Generated by Django 4.0.2 on 2022-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0002_alter_hydroshine_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='avto',
            name='kooficent',
            field=models.FloatField(max_length=3, verbose_name='Коофицент'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='wash',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
