# Generated by Django 4.0.2 on 2022-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0003_remove_applications_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Time',
            field=models.DateTimeField(unique=True, verbose_name='Время'),
        ),
    ]
