# Generated by Django 4.0.2 on 2022-06-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0004_alter_applications_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avtosite.time', verbose_name='Время'),
        ),
    ]
