# Generated by Django 4.0.2 on 2022-06-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0005_applications_date_update_alter_applications_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='day',
            field=models.BooleanField(default=False, verbose_name='Завтрашний день'),
        ),
    ]
