# Generated by Django 4.0.2 on 2022-06-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0007_time_time_alter_time_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.IntegerField(default=0, max_length=5, verbose_name='Время'),
        ),
    ]
