# Generated by Django 4.0.2 on 2022-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0009_alter_applications_hydroshine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='HydroShine',
            field=models.BooleanField(verbose_name='Hydro Shine'),
        ),
        migrations.DeleteModel(
            name='HydroShine',
        ),
    ]
