# Generated by Django 4.0.2 on 2022-06-21 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0010_alter_applications_hydroshine_delete_hydroshine'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='use',
            field=models.BooleanField(default=False, verbose_name='used'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Avto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='avtosite.avto', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате: "+79009009090"', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='avtosite.salon', verbose_name='Услуги для салона'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Time',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='avtosite.time', unique=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Wash',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='avtosite.wash', verbose_name='Услуги мойки кузова'),
        ),
    ]
