# Generated by Django 4.0.2 on 2022-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosite', '0012_alter_time_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='Done',
            field=models.BooleanField(default=False, verbose_name='Заявка исполнена'),
        ),
    ]
